name: Clean Old Configs
on:
  schedule:
    - cron: '0 */2 * * *'  # هر 2 ساعت یکبار در دقیقه 0ام
  workflow_dispatch:  # امکان اجرای دستی
permissions:
  contents: write
jobs:
  clean-configs:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت مخزن
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # دریافت کامل تاریخچه برای بررسی تغییرات
      
      - name: محدود کردن فایل به 100 خط آخر (در صورت نیاز)
        run: |
          # فقط اگر فایل وجود دارد و بیش از 100 خط دارد، آن را محدود کن
          if [ -f processed_configs.txt ] && [ $(wc -l < processed_configs.txt) -gt 100 ]; then
            echo "تعداد خطوط فعلی: $(wc -l < processed_configs.txt)"
            tail -n 100 processed_configs.txt > temp_file
            mv temp_file processed_configs.txt
            echo "فایل به 100 خط آخر محدود شد"
          else
            echo "فایل وجود ندارد یا کمتر/مساوی 100 خط دارد. تعداد خطوط: $(wc -l < processed_configs.txt || echo 0)"
          fi
      
      - name: Commit و Push تغییرات
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          if [ -f processed_configs.txt ]; then
            if git diff --quiet processed_configs.txt; then
              echo "هیچ تغییری برای کامیت وجود ندارد"
            else
              git add processed_configs.txt
              git commit -m "Auto-clean: محدود کردن processed_configs.txt به 100 خط آخر"
              git push origin HEAD:${{ github.ref_name }}
              echo "تغییرات با موفقیت push شد"
            fi
          else
            echo "فایلی برای commit وجود ندارد"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
