name: Scrape and Post Configs
on:
  schedule:
    - cron: '*/5 * * * *'  # هر 5 دقیقه
  workflow_dispatch:
jobs:
  scrape-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-telegram-bot
      - name: Run scraper
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python config_scraper.py
      - name: Commit processed configs
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add processed_configs.txt
          git commit -m "Update processed_configs.txt" || echo "No changes to commit"
          git push
